export const GALLERY_IMAGES = [
  {
    id: "dsc07124",
    src: "/image/galery/DSC07124.webp",
    alt: "Terapis Yamet mendampingi anak saat sesi permainan sensorik",
    category: "Kegiatan Terapi",
    featured: true,
  },
  {
    id: "dsc07129",
    src: "/image/galery/DSC07129.webp",
    alt: "Anak berlatih koordinasi motorik dengan alat bantu",
    category: "Kegiatan Terapi",
    featured: true,
  },
  {
    id: "dsc07136",
    src: "/image/galery/DSC07136.webp",
    alt: "Sesi asesmen perkembangan bersama terapis",
    category: "Kegiatan Terapi",
    featured: true,
  },
  {
    id: "dsc07148",
    src: "/image/galery/DSC07148.webp",
    alt: "Kegiatan kelompok untuk melatih interaksi sosial",
    category: "Kegiatan Terapi",
    featured: true,
  },
  {
    id: "dsc07160",
    src: "/image/galery/DSC07160.webp",
    alt: "Anak bermain puzzle sebagai bagian dari stimulasi kognitif",
    category: "Kegiatan Terapi",
    featured: true,
  },
  {
    id: "dsc07175",
    src: "/image/galery/DSC07175.webp",
    alt: "Orang tua berdiskusi dengan tim Yamet setelah sesi",
    category: "Kegiatan Terapi",
    featured: true,
  },
  {
    id: "aktifitas-ciytpbpqypap2uowu1gi",
    src: "/image/galery/aktifitas/ciytpbpqypap2uowu1gi.webp",
    alt: "Pendampingan terapi fisik dengan alat keseimbangan",
    category: "Kegiatan Terapi",
    featured: false,
  },
  {
    id: "aktifitas-eivz7ly59xmbhmwehndw",
    src: "/image/galery/aktifitas/eivz7ly59xmbhmwehndw.webp",
    alt: "Sesi terapi sensori menggunakan permainan warna",
    category: "Aktivitas Kreatif",
    featured: false,
  },
  {
    id: "aktifitas-gglmysp8karojptl9h1t",
    src: "/image/galery/aktifitas/gglmysp8karojptl9h1t.webp",
    alt: "Anak berlatih fokus melalui aktivitas kognitif",
    category: "Aktivitas Belajar",
    featured: false,
  },
  {
    id: "aktifitas-kyranex7wzyv64ylc4br",
    src: "/image/galery/aktifitas/kyranex7wzyv64ylc4br.webp",
    alt: "Interaksi kelompok kecil dengan pendamping terapis",
    category: "Aktivitas Sosial",
    featured: false,
  },
  {
    id: "aktifitas-mm5jke0khtiyano04u4n",
    src: "/image/galery/aktifitas/mm5jke0khtiyano04u4n.webp",
    alt: "Latihan motorik halus dengan permainan edukatif",
    category: "Aktivitas Motorik",
    featured: false,
  },
  {
    id: "aktifitas-mrmgddmzleozo5bv8rv4",
    src: "/image/galery/aktifitas/mrmgddmzleozo5bv8rv4.webp",
    alt: "Terapis memandu sesi koordinasi motorik kasar",
    category: "Motorik Kasar",
    featured: false,
  },
  {
    id: "aktifitas-p88gw18vwfwbprinxijt",
    src: "/image/galery/aktifitas/p88gw18vwfwbprinxijt.webp",
    alt: "Aktivitas permainan peran untuk melatih komunikasi",
    category: "Aktivitas Sosial",
    featured: false,
  },
  {
    id: "aktifitas-udfw3xkdyzcqrupbgfsq",
    src: "/image/galery/aktifitas/udfw3xkdyzcqrupbgfsq.webp",
    alt: "Anak mengeksplor alat terapi bersama instruktur",
    category: "Kegiatan Terapi",
    featured: false,
  },
  {
    id: "aktifitas-yhb6kfyw6cbtxs2vgxwg",
    src: "/image/galery/aktifitas/yhb6kfyw6cbtxs2vgxwg.webp",
    alt: "Pembelajaran kolaboratif dalam suasana ceria",
    category: "Aktivitas Belajar",
    featured: false,
  },
  {
    id: "aktifitas-zsgowbwyyofmflirjtij",
    src: "/image/galery/aktifitas/zsgowbwyyofmflirjtij.webp",
    alt: "Sesi relaksasi dan pendinginan setelah terapi",
    category: "Kegiatan Terapi",
    featured: false,
  },
  {
    id: "ash-gerlach",
    src: "/image/galery/ash-gerlach-YF6Xa6G98H4-unsplash.webp",
    alt: "Kelas seni bersama anak-anak",
    category: "Aktivitas Kreatif",
    featured: false,
  },
  {
    id: "bambi-corro",
    src: "/image/galery/bambi-corro-fn3puWB0pHY-unsplash.webp",
    alt: "Terapis membantu anak menulis huruf pertama",
    category: "Aktivitas Belajar",
    featured: false,
  },
  {
    id: "myles-tan",
    src: "/image/galery/myles-tan-WNAO036c6FM-unsplash.webp",
    alt: "Sesi bercerita bersama",
    category: "Aktivitas Sosial",
    featured: false,
  },
  {
    id: "nappy",
    src: "/image/galery/nappy-oxBV3sO9SmQ-unsplash.webp",
    alt: "Anak berlatih keseimbangan",
    category: "Motorik Kasar",
    featured: false,
  },
  {
    id: "sigmund",
    src: "/image/galery/sigmund-OV44gxH71DU-unsplash.webp",
    alt: "Sesi konseling bersama orang tua",
    category: "Konseling",
    featured: false,
  },
  {
    id: "stephen-andrews",
    src: "/image/galery/stephen-andrews-u0zTce7KNlY-unsplash.webp",
    alt: "Anak mengeksplor permainan konstruktif",
    category: "Aktivitas Motorik",
    featured: false,
  },
];