export const GALLERY_IMAGES = [
  {
    id: "dsc07124",
    src: "/image/galery/DSC07124.JPG",
    alt: "Terapis Yamet mendampingi anak saat sesi permainan sensorik",
    category: "Kegiatan Terapi",
    featured: true,
  },
  {
    id: "dsc07129",
    src: "/image/galery/DSC07129.JPG",
    alt: "Anak berlatih koordinasi motorik dengan alat bantu",
    category: "Kegiatan Terapi",
    featured: true,
  },
  {
    id: "dsc07136",
    src: "/image/galery/DSC07136.JPG",
    alt: "Sesi asesmen perkembangan bersama terapis",
    category: "Kegiatan Terapi",
    featured: true,
  },
  {
    id: "dsc07148",
    src: "/image/galery/DSC07148.JPG",
    alt: "Kegiatan kelompok untuk melatih interaksi sosial",
    category: "Kegiatan Terapi",
    featured: true,
  },
  {
    id: "dsc07160",
    src: "/image/galery/DSC07160.JPG",
    alt: "Anak bermain puzzle sebagai bagian dari stimulasi kognitif",
    category: "Kegiatan Terapi",
    featured: true,
  },
  {
    id: "dsc07175",
    src: "/image/galery/DSC07175.JPG",
    alt: "Orang tua berdiskusi dengan tim Yamet setelah sesi",
    category: "Kegiatan Terapi",
    featured: true,
  },
  {
    id: "ash-gerlach",
    src: "/image/galery/ash-gerlach-YF6Xa6G98H4-unsplash.webp",
    alt: "Kelas seni bersama anak-anak",
    category: "Aktivitas Kreatif",
    featured: false,
  },
  {
    id: "bambi-corro",
    src: "/image/galery/bambi-corro-fn3puWB0pHY-unsplash.webp",
    alt: "Terapis membantu anak menulis huruf pertama",
    category: "Aktivitas Belajar",
    featured: false,
  },
  {
    id: "myles-tan",
    src: "/image/galery/myles-tan-WNAO036c6FM-unsplash.webp",
    alt: "Sesi bercerita bersama",
    category: "Aktivitas Sosial",
    featured: false,
  },
  {
    id: "nappy",
    src: "/image/galery/nappy-oxBV3sO9SmQ-unsplash.webp",
    alt: "Anak berlatih keseimbangan",
    category: "Motorik Kasar",
    featured: false,
  },
  {
    id: "sigmund",
    src: "/image/galery/sigmund-OV44gxH71DU-unsplash.webp",
    alt: "Sesi konseling bersama orang tua",
    category: "Konseling",
    featured: false,
  },
  {
    id: "stephen-andrews",
    src: "/image/galery/stephen-andrews-u0zTce7KNlY-unsplash.webp",
    alt: "Anak mengeksplor permainan konstruktif",
    category: "Aktivitas Motorik",
    featured: false,
  },
];
